--상품 설명을 추가하기 위해
--OPRODUCT 테이블에 PDTDESCRIPTION 칼럼 추가 및 값 추가

ALTER TABLE OPRODUCT
ADD ("PDTDESCRIPTION" NVARCHAR2(200));

SELECT *
FROM OPRODUCT;

UPDATE OPRODUCT SET PDTDESCRIPTION = '순하고 깔끔한 저자극 리무버'
WHERE PDTID = 169;

UPDATE OPRODUCT SET PDTDESCRIPTION = '광택과 볼륨감을 더하는 탑젤'
WHERE PDTID = 170;

UPDATE OPRODUCT SET PDTDESCRIPTION = '식물성 오일로 손발톱을 건강하게'
WHERE PDTID = 171;

UPDATE OPRODUCT SET PDTDESCRIPTION = '강력한 보호막을 형성하는 네일 강화제'
WHERE PDTID = 172;

UPDATE OPRODUCT SET PDTDESCRIPTION = '부착, 제거 팁으로 전문가처럼'
WHERE PDTID = 173;

UPDATE OPRODUCT SET PDTDESCRIPTION = '유지력을 높여주는 네일 프라이머'
WHERE PDTID = 174;

UPDATE OPRODUCT SET PDTDESCRIPTION = '안전하고 깔끔한 손·발톱 관리'
WHERE PDTID = 175;

UPDATE oproduct
SET pdtcount = 50
WHERE pdtid BETWEEN 1 AND 182;
--
UPDATE opdtoption
SET optcount = 50
WHERE optid BETWEEN 1 AND 28;

COMMIT;
