-- 시퀀스 생성
CREATE SEQUENCE OUSERSEQ NOCACHE;
CREATE SEQUENCE OORDERSEQ NOCACHE;
CREATE SEQUENCE OORDDETAILSEQ NOCACHE;
CREATE SEQUENCE ADDCARTSEQ NOCACHE;
CREATE SEQUENCE OADDRSEQ NOCACHE;

/* 멤버십 */
CREATE TABLE OMEMBERSHIP (
    MEMID NUMBER NOT NULL,
    MEMNAME VARCHAR2(10),
    MEMBENEFIT NUMBER,
    MEMGRADETIER NUMBER,
    CONSTRAINT PKOMEMBERSHIP PRIMARY KEY (MEMID)
);

/* 권한 */
CREATE TABLE OAUTH (
    AUTHID NUMBER NOT NULL,
    AUTHNAME VARCHAR2(20),
    CONSTRAINT PKOAUTH PRIMARY KEY (AUTHID)
);

/* 카테고리 */
CREATE TABLE OCATEGORY (
    CATID NUMBER NOT NULL,
    CATNAME NVARCHAR2(20) NOT NULL,
    CONSTRAINT PKOCATEGORY PRIMARY KEY (CATID)
);

/* 하위카테고리 */
CREATE TABLE OSUBCATEGORY (
    SCATID NUMBER NOT NULL,
    SCATNAME NVARCHAR2(20) NOT NULL,
    CONSTRAINT PKOSUBCATEGORY PRIMARY KEY (SCATID)
);

/* 회원 */
CREATE TABLE OUSER (
    USERID NUMBER NOT NULL,
    MEMID NUMBER,
    AUTHID NUMBER,
    USERLOGINID VARCHAR2(20) NOT NULL,
    USERPASSWORD VARCHAR2(100) NOT NULL,
    USERNAME NVARCHAR2(10) NOT NULL,
    USEREMAIL VARCHAR2(100) NOT NULL,
    USERTEL VARCHAR2(20) NOT NULL,
    USERBIRTH DATE NOT NULL,
    USERPOINT NUMBER DEFAULT 0,
    USERSNSAGREE CHAR(1) DEFAULT 'N',
    USERJOINDATE DATE,
    CONSTRAINT PKOUSER PRIMARY KEY (USERID),
    CONSTRAINT UKOUSER UNIQUE (USERLOGINID, USEREMAIL),
    CONSTRAINT FKOMEMBERSHIPTOOUSER FOREIGN KEY (MEMID) REFERENCES OMEMBERSHIP (MEMID),
    CONSTRAINT FKOAUTHTOOUSER FOREIGN KEY (AUTHID) REFERENCES OAUTH (AUTHID)
);

/* 상품 */
CREATE TABLE OPRODUCT (
    PDTID NUMBER NOT NULL,
    CATID NUMBER,
    SCATID NUMBER,
    PDTNUMBER NUMBER DEFAULT 0,
    PDTNAME NVARCHAR2(50) NOT NULL,
    PDTAMOUNT NUMBER,
    PDTDISCOUNTRATE NUMBER DEFAULT 0,
    PDTIMGURL VARCHAR2(100),
    PDTCOUNT NUMBER DEFAULT 0 NOT NULL,
    PDTREVIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
    PDTSALESCOUNT NUMBER DEFAULT 0 NOT NULL,
    PDTADDDATE DATE NOT NULL,
    PDTVIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
    PDTIMGURL2 VARCHAR2(100),
    CONSTRAINT PKOPRODUCT PRIMARY KEY (PDTID),
    CONSTRAINT FKOCATEGORYTOOPRODUCT FOREIGN KEY (CATID) REFERENCES OCATEGORY (CATID),
    CONSTRAINT FKOSUBCATEGORYTOOPRODUCT FOREIGN KEY (SCATID) REFERENCES OSUBCATEGORY (SCATID)
);

/* 주문 */
CREATE TABLE OORDER (
    ORDPK NUMBER NOT NULL,
    ORDID VARCHAR2(30) NOT NULL,
    USERID NUMBER,
    ICPNID NUMBER,
    ORDNAME NVARCHAR2(10),
    ORDADDRESS NVARCHAR2(200),
    ORDZIPCODE CHAR(5) NOT NULL,
    ORDTEL VARCHAR2(20),
    ORDEMAIL VARCHAR2(100),
    ORDPASSWORD VARCHAR2(50),
    ORDORDERDATE DATE,
    ORDTOTALAMOUNT NUMBER DEFAULT 0,
    ORDCPNDISCOUNT NUMBER DEFAULT 0,
    ORDPDTDISCOUNT NUMBER DEFAULT 0,
    ORDUSEPOINT NUMBER,
    ORDPAYOPTION VARCHAR2(30),
    ORDDELIVERYFEE NUMBER DEFAULT 3000,
    CONSTRAINT PKOORDER PRIMARY KEY (ORDPK),
    CONSTRAINT FKOUSERTOOORDER FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 주문상세 */
CREATE TABLE OORDDETAIL (
    OPDTID NUMBER NOT NULL,
    ORDPK NUMBER NOT NULL,
    OPDTNAME NVARCHAR2(50),
    OPDTAMOUNT NUMBER DEFAULT 0,
    OPDTDCAMOUNT NUMBER DEFAULT 0,
    OPDTOPNAME NVARCHAR2(20),
    OPDTOPAMOUNT NUMBER DEFAULT 0,
    OPDTCOUNT NUMBER,
    OPDTSTATE NVARCHAR2(30),
    OPDTREFUND NVARCHAR2(30),
    OPDTDELCOMPANY NVARCHAR2(30),
    OPDTDELNUMBER VARCHAR2(30),
    OPDTCONFIRM CHAR(1) DEFAULT 'N',
    CONSTRAINT PKOORDDETAIL PRIMARY KEY (OPDTID, ORDPK),
    CONSTRAINT FKOORDERTOOORDDETAIL FOREIGN KEY (ORDPK) REFERENCES OORDER (ORDPK)
);

/* 리뷰 */
CREATE TABLE OREVIEW (
    REVID NUMBER NOT NULL,
    USERID NUMBER,
    ORDPK NUMBER,
    OPDTID NUMBER,
    REVCONTENT VARCHAR2(1500) NOT NULL,
    REVWRITEDATE DATE NOT NULL,
    REVRATING NUMBER(1) DEFAULT 5 NOT NULL,
    REVGOODCOUNT NUMBER DEFAULT 0,
    REVBADCOUNT NUMBER,
    REVCOMMENTCOUNT NUMBER DEFAULT 0,
    REVISRECOMMEND CHAR(1) DEFAULT 'N',
    REVISPHOTO CHAR(1) DEFAULT 'N',
    REVAGEGROUP VARCHAR2(20),
    REVOPTION VARCHAR2(20),
    CONSTRAINT PKOREVIEW PRIMARY KEY (REVID),
    CONSTRAINT FKOUSERTOOREVIEW FOREIGN KEY (USERID) REFERENCES OUSER (USERID),
    CONSTRAINT FKOORDDETAILTOOREVIEW FOREIGN KEY (OPDTID, ORDPK) REFERENCES OORDDETAIL (OPDTID, ORDPK)
);

/* 쿠폰 */
CREATE TABLE OCOUPON (
    CPNID NUMBER NOT NULL,
    CPNDISCOUNTRATE NUMBER,
    CPNINFO NVARCHAR2(50),
    CPNSTARTDATE DATE,
    CPNAPPLY CHAR(1) DEFAULT 'P',
    CPNENDDATE DATE,
    CPNMAXAMOUNT NUMBER,
    CPNCONVALUE VARCHAR2(30),
    CPNCONTYPE VARCHAR2(15),
    CPNDISCOUNTTYPE CHAR(1),
    CONSTRAINT PKOCOUPON PRIMARY KEY (CPNID)
);

/* 결제 */
CREATE TABLE OPAYMENT (
    PAYID NUMBER NOT NULL,
    ORDPK NUMBER NOT NULL,
    USERID NUMBER,
    PAYAMOUNT NUMBER,
    PAYDATE DATE,
    PAYOPTION VARCHAR2(30),
    PAYSTATE VARCHAR2(30),
    PAYTRADENUMBER VARCHAR2(30),
    CONSTRAINT PKOPAYMENT PRIMARY KEY (PAYID, ORDPK),
    CONSTRAINT UKOPAYMENT UNIQUE (PAYTRADENUMBER),
    CONSTRAINT FKOORDERTOOPAYMENT FOREIGN KEY (ORDPK) REFERENCES OORDER (ORDPK),
    CONSTRAINT FKOUSERTOOPAYMENT FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 댓글 */
CREATE TABLE OCOMMENT (
    CMTID NUMBER NOT NULL,
    REVID NUMBER,
    USERID NUMBER,
    CMTWRITEDATE DATE NOT NULL,
    CMTCONTENT CLOB NOT NULL,
    CONSTRAINT PKOCOMMENT PRIMARY KEY (CMTID),
    CONSTRAINT FKOREVIEWTOOCOMMENT FOREIGN KEY (REVID) REFERENCES OREVIEW (REVID),
    CONSTRAINT FKOUSERTOOCOMMENT FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 라인업 */
CREATE TABLE OLINEUP (
    LINEUPID NUMBER NOT NULL,
    LINEUPOPTION NVARCHAR2(20) NOT NULL,
    CONSTRAINT PKOLINEUP PRIMARY KEY (LINEUPID)
);

/* 디자인 */
CREATE TABLE ODESIGN (
    DESIGNID NUMBER NOT NULL,
    DESIGNOPTION NVARCHAR2(20) NOT NULL,
    CONSTRAINT PKODESIGN PRIMARY KEY (DESIGNID)
);

/* 컬러 */
CREATE TABLE OCOLOR (
    COLORID NUMBER NOT NULL,
    COLOROPTION NVARCHAR2(20) NOT NULL,
    CONSTRAINT PKOCOLOR PRIMARY KEY (COLORID)
);

/* 장바구니 목록 */
CREATE TABLE OCARTLIST (
    CLISTID NUMBER NOT NULL,
    USERID NUMBER,
    PDTID NUMBER,
    OPTID NUMBER,
    CLISTPDTCOUNT NUMBER,
    CLISTADDDATE DATE,
    CLISTSELECT CHAR(1) DEFAULT 'Y',
    CONSTRAINT PKOCARTLIST PRIMARY KEY (CLISTID),
    CONSTRAINT FKOUSERTOOCARTLIST FOREIGN KEY (USERID) REFERENCES OUSER (USERID),
    CONSTRAINT FKOPRODUCTTOOCARTLIST FOREIGN KEY (PDTID) REFERENCES OPRODUCT (PDTID)
);

/* 발급쿠폰 */
CREATE TABLE OISSUEDCOUPON (
    ICPNID NUMBER NOT NULL,
    USERID NUMBER,
    CPNID NUMBER,
    ICPNISSUEDATE DATE,
    ICPNISUSED CHAR(1) DEFAULT 'N',
    CONSTRAINT PKOISSUEDCOUPON PRIMARY KEY (ICPNID),
    CONSTRAINT FKOUSERTOOISSUEDCOUPON FOREIGN KEY (USERID) REFERENCES OUSER (USERID),
    CONSTRAINT FKOCOUPONTOOISSUEDCOUPON FOREIGN KEY (CPNID) REFERENCES OCOUPON (CPNID)
);

/* 배송지 */
CREATE TABLE OADDRESS (
    ADDRID NUMBER NOT NULL,
    USERID NUMBER,
    ADDRNICK NVARCHAR2(20) NOT NULL,
    ADDRNAME NVARCHAR2(10) NOT NULL,
    ADDRHTEL VARCHAR2(20),
    ADDRTEL VARCHAR2(20) NOT NULL,
    ADDRADDRESSMAIN NVARCHAR2(100) NOT NULL,
    ADDRADDRESSDETAIL NVARCHAR2(100),
    ADDRZIPCODE CHAR(5) NOT NULL,
    ADDRMAIN CHAR(1) DEFAULT 'N',
    CONSTRAINT PKOADDRESS PRIMARY KEY (ADDRID),
    CONSTRAINT FKOUSERTOOADDRESS FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 상품옵션 */
CREATE TABLE OPDTOPTION (
    OPTID NUMBER NOT NULL,
    PDTID NUMBER,
    OPTNAME NVARCHAR2(20) NOT NULL,
    OPTAMOUNT NUMBER DEFAULT 0,
    OPTCOUNT NUMBER DEFAULT 0,
    CONSTRAINT PKOPDTOPTION PRIMARY KEY (OPTID),
    CONSTRAINT FKOPRODUCTTOOPDTOPTION FOREIGN KEY (PDTID) REFERENCES OPRODUCT (PDTID)
);

/* 상품별 컬러 항목 */
CREATE TABLE OPDTCOLOR (
    PDTID NUMBER,
    COLORID NUMBER,
    CONSTRAINT FKOPRODUCTTOOPDTCOLOR FOREIGN KEY (PDTID) REFERENCES OPRODUCT (PDTID),
    CONSTRAINT FKOCOLORTOOPDTCOLOR FOREIGN KEY (COLORID) REFERENCES OCOLOR (COLORID)
);

/* 상품별 라인업 항목 */
CREATE TABLE OPDTLINEUP (
    PDTID NUMBER,
    LINEUPID NUMBER,
    CONSTRAINT FKOPRODUCTTOOPDTLINEUP FOREIGN KEY (PDTID) REFERENCES OPRODUCT (PDTID),
    CONSTRAINT FKOLINEUPTOOPDTLINEUP FOREIGN KEY (LINEUPID) REFERENCES OLINEUP (LINEUPID)
);

/* 상품별 디자인 항목 */
CREATE TABLE OPDTDESIGN (
    PDTID NUMBER,
    DESIGNID NUMBER,
    CONSTRAINT FKOPRODUCTTOOPDTDESIGN FOREIGN KEY (PDTID) REFERENCES OPRODUCT (PDTID),
    CONSTRAINT FKODESIGNTOOPDTDESIGN FOREIGN KEY (DESIGNID) REFERENCES ODESIGN (DESIGNID)
);

/* FAQ카테고리 */
CREATE TABLE OFAQCATEGORY (
    FCATID NUMBER NOT NULL,
    FCATNAME NVARCHAR2(15),
    CONSTRAINT PKOFAQCATEGORY PRIMARY KEY (FCATID)
);

/* FAQ */
CREATE TABLE OFAQ (
    FAQID NUMBER NOT NULL,
    FCATID NUMBER,
    USERID NUMBER NOT NULL,
    FAQTITLE NVARCHAR2(50) NOT NULL,
    FAQCONTENT VARCHAR2(3000),
    FAQWRITER NVARCHAR2(10),
    FAQVIEWCOUNT NUMBER DEFAULT 0,
    FAQWRITEDATE DATE,
    FAQMODIFYDATE DATE,
    CONSTRAINT PKOFAQ PRIMARY KEY (FAQID),
    CONSTRAINT FKOFAQCATEGORYTOOFAQ FOREIGN KEY (FCATID) REFERENCES OFAQCATEGORY (FCATID),
    CONSTRAINT FKOUSERTOOFAQ FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* NOTICE */
CREATE TABLE ONOTICE (
    NOTICEID NUMBER NOT NULL,
    USERID NUMBER NOT NULL,
    NOTICETITLE NVARCHAR2(50) NOT NULL,
    NOTICECONTENT VARCHAR2(3000),
    NOTICEWRITER NVARCHAR2(10),
    NOTICEVIEWCOUNT NUMBER DEFAULT 0,
    NOTICEWRITEDATE DATE,
    NOTICEMODIFYDATE DATE,
    CONSTRAINT PKONOTICE PRIMARY KEY (NOTICEID),
    CONSTRAINT FKOUSERTOONOTICE FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 1:1게시판 */
CREATE TABLE OASK (
    ASKID NUMBER NOT NULL,
    USERID NUMBER,
    ASKTITLE NVARCHAR2(50),
    ASKCONTENT VARCHAR2(3000),
    ASKWRITER NVARCHAR2(10),
    ASKWRITEDATE DATE,
    ASKMODIFYDATE DATE,
    ASKISANSWER CHAR(1) DEFAULT 'X',
    CONSTRAINT PKOASK PRIMARY KEY (ASKID),
    CONSTRAINT FKOUSERTOOASK FOREIGN KEY (USERID) REFERENCES OUSER (USERID)
);

/* 리뷰URL */
CREATE TABLE OREVURL (
    RURLID NUMBER NOT NULL,
    REVID NUMBER NOT NULL,
    RURLPHOTO VARCHAR2(100),
    RURLRECORD VARCHAR2(100),
    CONSTRAINT PKOREVURL PRIMARY KEY (RURLID, REVID),
    CONSTRAINT FKOREVIEWTOOREVURL FOREIGN KEY (REVID) REFERENCES OREVIEW (REVID)
);

/* URL 컬럼 크기 변경 */
ALTER TABLE OPRODUCT MODIFY PDTIMGURL VARCHAR2(100 CHAR);
ALTER TABLE OPRODUCT MODIFY PDTIMGURL2 VARCHAR2(100 CHAR);

/* 이벤트 */
CREATE TABLE OEVENT (
    EVTID NUMBER NOT NULL,
    EVTTITLE NVARCHAR2(50),
    EVTCONTENT VARCHAR2(3000),
    EVTSTARTDATE DATE NOT NULL,
    EVTENDDATE DATE NOT NULL,
    EVTCONTENTURL VARCHAR2(50),
    CONSTRAINT PKOEVENT PRIMARY KEY (EVTID)
);

COMMIT;
